"""SQLAlchemy 2.x ORM models for PECP persistence.

ResourceRecord stores the persisted shape for a submitted resource spec.
The full validated ResourceSpec is stored as JSON in spec_json for portability.
"""

from datetime import datetime, timezone

from sqlalchemy import DateTime, String, Text, UniqueConstraint
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class ResourceRecord(Base):
    """ORM model for a persisted resource request.

    id is a UUID4 hex string generated by the route handler.
    spec_json holds the validated ResourceSpec serialized via model_dump_json().
    """

    __tablename__ = "resource_records"
    __table_args__ = (
        UniqueConstraint("team", "kind", "name", name="uq_resource_team_kind_name"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True)
    team: Mapped[str] = mapped_column(String, index=True, nullable=False)
    kind: Mapped[str] = mapped_column(String, nullable=False)
    name: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False, default="pending")
    spec_json: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    provider_metadata: Mapped[str | None] = mapped_column(Text, nullable=True, default="{}")
    activity_log: Mapped[str | None] = mapped_column(Text, nullable=True, default="[]")
    env: Mapped[str | None] = mapped_column(Text, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True, default="[]")
