apiVersion: pecp/v1
kind: PECPLambda
metadata:
  name: hello-world
  team: customer-product-app
  env: dev
spec:
  name: hello-world
  exposure: private
  api-gateway: /hello
  source-code: github://customer-product-app/lambda-hello
