apiVersion: pecp/v1
kind: PECPLambda
metadata:
  name: audit-trail-lambda
  team: customer-product-app
  env: staging
spec:
  name: audit-trail-lambda
  exposure: private
  api-gateway: /audit
  source-code: github://customer-product-app/audit-lambda
