apiVersion: pecp/v1
kind: PECPLambda
metadata:
  name: webhook-handler
  team: customer-product-app
  env: prod
spec:
  name: webhook-handler
  exposure: public
  api-gateway: /customer-product-app/webhook
  source-code: github://customer-product-app/webhook-lambda
