apiVersion: pecp/v1
kind: PECPLambda
metadata:
  name: health-check
  team: customer-product-app
  env: dev
spec:
  name: health-check
  exposure: private
  api-gateway: /health
  source-code: github://customer-product-app/health-check-lambda
